// SPDX-FileCopyrightText: Copyright 2026 Kyris
// SPDX-License-Identifier: Apache-2.0
use std::path::PathBuf;

use crate::config_writer::{NoopValidator, WellFormedJsonValidator};
use crate::integration::{
    read_json_value, set_json_string_path, set_json_value_path, write_json_value,
};
use crate::state::{restore_manifest_entry_component, write_managed_file};

use super::probe::{
    ProbeResult, fingerprint, json_has_any_mcp_servers, json_has_mcp_wrap, not_detected,
};
use super::registry::{
    AgentDescriptor, AgentIntegrationPlan, AllowResponse, AttributionMechanism,
    BurnControlMechanism, ExecutionMechanism, HookProtocol, McpConfigFormat, McpConfigLocation,
    SurfaceIntegration, ToolMapping, ToolMechanism, which_exists,
};

pub struct Cline;

// All paths target the STANDALONE `cline` CLI (`~/.cline/...`), not the VS Code
// extension. The extension's `CLINE_COMMAND_PERMISSIONS` env / launchd / VS Code
// globalStorage approach is gone — the CLI never read that env var.
fn cline_settings_dir() -> Result<PathBuf, String> {
    Ok(crate::integration::home_dir()?
        .join(".cline")
        .join("data")
        .join("settings"))
}

/// Provider settings the CLI reads (`{providers:{<id>:{baseUrl,apiKey,headers}}}`).
pub fn cline_providers_path() -> Result<PathBuf, String> {
    Ok(cline_settings_dir()?.join("providers.json"))
}

pub fn cline_mcp_settings_path() -> Result<PathBuf, String> {
    Ok(cline_settings_dir()?.join("cline_mcp_settings.json"))
}

/// The file-hook lives in the CLI's auto-discovered hooks dir; a file whose name
/// is `PreToolUse` is mapped to cline's `tool_call` event and run (blocking) on
/// every tool call. Named `.cjs` so `node` loads it with `require`.
fn cline_hook_path() -> Result<PathBuf, String> {
    Ok(crate::integration::home_dir()?
        .join(".cline")
        .join("hooks")
        .join("PreToolUse.cjs"))
}

fn cline_cli_installed() -> bool {
    which_exists("cline")
}

fn cline_detected() -> bool {
    cline_cli_installed()
        || cline_hook_path().is_ok_and(|p| p.exists())
        || cline_providers_path().is_ok_and(|p| p.exists())
}

/// The cline file-hook bridge. cline delivers a different hook shape than the
/// native-hook agents (JSON tool context in, a JSON `{cancel}` control out), so
/// this reshapes cline's payload into the kyris payload, asks the SHARED decision
/// engine (`kyris hook check --agent cline` → agentpactd), and blocks the tool by
/// emitting `{cancel:true}` on deny. The decision engine + `HookProtocol` are
/// shared with every other agent; only this thin per-agent bridge differs.
fn cline_hook_source() -> &'static str {
    r#"// SPDX-FileCopyrightText: Copyright 2026 Kyris
// SPDX-License-Identifier: Apache-2.0
// Generated by Kyris — AgentPact live governance for cline (file-hook bridge).
// cline runs this on every tool call (PreToolUse -> tool_call), blocking. It
// reshapes cline's payload into the kyris hook payload, asks the shared decision
// engine (kyris hook check -> agentpactd), and blocks the tool by emitting a
// {cancel:true} control object when governance denies.
const { spawnSync } = require("node:child_process")
const { existsSync } = require("node:fs")
const { homedir } = require("node:os")

// Prefer the managed copy, then well-known install paths, then PATH — mirrors the
// shell adapter's resolution (a real binary at a known path over whatever PATH is).
function kyrisBin() {
  for (const c of [
    homedir() + "/.kyris/bin/kyris",
    homedir() + "/.local/bin/kyris",
    "/opt/homebrew/bin/kyris",
    "/usr/local/bin/kyris",
  ]) {
    if (existsSync(c)) return c
  }
  return "kyris"
}

// cline runtime tool name -> the detail kyris governs (command for execute,
// path for write). run_commands carries an ARRAY of commands, joined into one
// compound so agentpactd splits it into per-segment decisions.
function detailFor(name, input) {
  input = input || {}
  if (name === "run_commands") return Array.isArray(input.commands) ? input.commands.join(" && ") : ""
  if (name === "editor") return typeof input.path === "string" ? input.path : ""
  if (name === "apply_patch") return typeof input === "string" ? input : (typeof input.input === "string" ? input.input : "")
  return ""
}

let raw = ""
process.stdin.on("data", (d) => { raw += d })
process.stdin.on("end", () => {
  let p = {}
  try { p = JSON.parse(raw) } catch { p = {} }
  const tc = p.tool_call || {}
  // cwd is the permitted-domain anchor agentpactd resolves policy from; cline has
  // no top-level cwd, so use the first workspace root.
  const cwd = (Array.isArray(p.workspaceRoots) && p.workspaceRoots[0]) ||
    (p.workspaceInfo && p.workspaceInfo.rootPath) || process.cwd()
  const payload = JSON.stringify({
    tool_name: tc.name,
    tool_input: { detail: detailFor(tc.name, tc.input) },
    cwd,
  })
  const res = spawnSync(kyrisBin(), ["hook", "check", "--agent", "cline"], {
    input: payload,
    cwd,
    encoding: "utf8",
    timeout: 600000,
    env: { ...process.env, KYRIS_GOVERNED_SUBPROCESS: "cline" },
  })
  // Fail OPEN if the binary can't run (not found / timeout) — matches the shell
  // adapter's "kyris not found -> ungoverned" posture.
  if (res.error) { process.stdout.write("{}"); return }
  // exit 0 = allow; nonzero (2 = deny) blocks this tool call. cline reads the
  // JSON control object from stdout (not the exit code), so emit {cancel:true}.
  if (res.status !== 0) {
    const reason = (res.stderr || res.stdout || "").trim().replace(/^\[agentpact\]\s*/, "")
    process.stdout.write(JSON.stringify({ cancel: true, errorMessage: reason || "blocked by kyris governance" }))
  } else {
    process.stdout.write("{}")
  }
})
"#
}

/// Current providers.json as a JSON value, or an empty object if absent.
fn read_or_empty_providers(path: &std::path::Path) -> Result<serde_json::Value, String> {
    if path.exists() {
        read_json_value(path)
    } else {
        Ok(serde_json::Value::Object(serde_json::Map::new()))
    }
}

impl AgentDescriptor for Cline {
    fn id(&self) -> &'static str {
        "cline"
    }
    fn display_name(&self) -> &'static str {
        "Cline"
    }
    fn is_installed(&self) -> bool {
        cline_detected()
    }
    fn probe(&self) -> ProbeResult {
        use super::profile::SurfaceState;
        if !cline_detected() {
            return not_detected();
        }

        // Live-hook adapter: the kyris governance file-hook is present.
        let has_live_hook = cline_hook_path().is_ok_and(|p| p.exists());
        let execution = if has_live_hook {
            SurfaceState::adapted(ExecutionMechanism::LiveHookAdapter)
        } else {
            SurfaceState::none()
        };

        let mcp_path = cline_mcp_settings_path().ok();
        let has_mcp_wrap = mcp_path
            .as_deref()
            .is_some_and(|p| json_has_mcp_wrap(p, "mcpServers"));
        let has_any_mcp_servers = mcp_path
            .as_deref()
            .is_some_and(|p| json_has_any_mcp_servers(p, "mcpServers"));
        let tool = if has_mcp_wrap {
            SurfaceState::adapted(ToolMechanism::McpWrapping)
        } else if !has_any_mcp_servers {
            SurfaceState::not_applicable()
        } else {
            SurfaceState::none()
        };

        let has_base_url_rewrite = cline_providers_path().ok().is_some_and(|p| {
            read_json_value(&p).is_ok_and(|v| {
                v.get("providers")
                    .and_then(|providers| providers.get("anthropic"))
                    .and_then(|a| a.get("settings"))
                    .and_then(|s| s.get("baseUrl"))
                    .and_then(|u| u.as_str())
                    .is_some_and(|u| !u.is_empty())
            })
        });
        let burn_control = if has_base_url_rewrite {
            SurfaceState::adapted(BurnControlMechanism::ConfigRewrite)
        } else {
            SurfaceState::none()
        };

        let mut managed_files = Vec::new();
        if let Some(path) = mcp_path.as_deref()
            && let Some(fp) = fingerprint(path)
        {
            managed_files.push(fp);
        }
        if let Some(fp) = cline_hook_path().ok().and_then(|p| fingerprint(&p)) {
            managed_files.push(fp);
        }
        ProbeResult {
            detected: true,
            execution,
            tool,
            burn_control,
            managed_files,
        }
    }
    fn kyris_content_markers(&self) -> &'static [&'static str] {
        &["kyris hook check", "kyris-mcp"]
    }
    fn integration_plan(&self) -> AgentIntegrationPlan {
        super::capabilities::apply_declared_capabilities(
            self.canonical_id(),
            AgentIntegrationPlan {
                // cline's file-hook system (PreToolUse -> tool_call) gives a real
                // live-hook adapter — the kyris bridge blocks tool calls in real
                // time via `kyris hook check` -> agentpactd, like the native-hook
                // agents.
                execution: SurfaceIntegration::adapted(&[ExecutionMechanism::LiveHookAdapter]),
                tool: SurfaceIntegration::adapted(&[ToolMechanism::McpWrapping]),
                burn_control: SurfaceIntegration::adapted(&[BurnControlMechanism::ConfigRewrite]),
                attribution: &[
                    AttributionMechanism::KyrisPathShim,
                    AttributionMechanism::NativeHookPayload,
                    AttributionMechanism::ProcessLineage,
                ],
                agentpact_native_attribution: false,
            },
        )
    }
    fn hook_protocol(&self) -> Option<HookProtocol> {
        // The bridge normalizes every cline tool to `tool_input.detail`, so all
        // mappings share `detail_key = "detail"` (the right string per action:
        // command for execute, path for write).
        let detail = || Some("detail".to_string());
        Some(HookProtocol {
            tool_name_field: "tool_name".to_string(),
            detail_fields: vec!["tool_input".to_string()],
            tool_mappings: vec![
                ToolMapping {
                    tool_name: "run_commands".to_string(),
                    action: "execute".to_string(),
                    detail_key: detail(),
                },
                ToolMapping {
                    tool_name: "editor".to_string(),
                    action: "write".to_string(),
                    detail_key: detail(),
                },
                ToolMapping {
                    tool_name: "apply_patch".to_string(),
                    action: "write".to_string(),
                    detail_key: detail(),
                },
            ],
            // Reads + cline-internal tools: skip the daemon (mirrors the other
            // agents' pass-through lists).
            pass_through_tools: [
                "read_files",
                "fetch_web_content",
                "search_codebase",
                "ask_question",
                "skills",
                "submit_and_exit",
                "commit",
            ]
            .into_iter()
            .map(String::from)
            .collect(),
            detail_pass_throughs: Vec::new(),
            default_action: "call".to_string(),
            // The bridge reads `kyris hook check`'s EXIT CODE (0 allow / 2 deny),
            // not stdout, so the allow shape is the empty default.
            allow_response: AllowResponse::EmptyStdout,
        })
    }
    fn configure_execution_surface(
        &self,
        _base_url: &str,
        _inbound_key: &str,
        _agent_specific: &std::collections::HashMap<String, String>,
    ) -> Result<Vec<String>, String> {
        let hook_path = cline_hook_path()?;
        let mut changes = Vec::new();
        // Auto-discovered file-hook: just write it (no config registration). The
        // bridge is opaque JS — no schema to validate.
        if write_managed_file(
            &hook_path,
            cline_hook_source(),
            "cline:execution",
            Some(0o644),
            &NoopValidator,
        )? {
            changes.push(format!("wrote {}", hook_path.display()));
        }
        Ok(changes)
    }
    fn mcp_config(&self) -> Option<McpConfigLocation> {
        cline_mcp_settings_path()
            .ok()
            .map(|path| McpConfigLocation {
                path,
                format: McpConfigFormat::Json {
                    servers_path: vec!["mcpServers"],
                },
            })
    }
    fn burn_control_config_paths(&self) -> Vec<PathBuf> {
        cline_providers_path().into_iter().collect()
    }
    fn configure_tool_surface(
        &self,
        base_url: &str,
        inbound_key: &str,
        _agent_specific: &std::collections::HashMap<String, String>,
    ) -> Result<Vec<String>, String> {
        // cline has no per-server MCP tool-denylist field (only whole-server
        // `disabled`/`autoApprove`), so it uses the default (no) extra filter and
        // relies on the runtime wrap/routing backstop — see configure.rs.
        super::configure::configure_json_mcp_tool_surface(self, base_url, inbound_key)
    }
    fn configure_burn_control_surface(
        &self,
        base_url: &str,
        inbound_key: &str,
        _agent_specific: &std::collections::HashMap<String, String>,
    ) -> Result<Vec<String>, String> {
        let path = cline_providers_path()?;
        let agent_id = self.canonical_id();
        let base_url_v1 = format!("{base_url}/v1");

        let mut config = read_or_empty_providers(&path)?;
        let mut config_changed = false;
        // providers.json is the StoredProviderSettings store: a versioned file whose
        // per-provider entry is `{settings:{…}, updatedAt, tokenSource}` (the runtime
        // applies `stored.baseUrl`/`stored.headers` — local-runtime-bootstrap.ts).
        // The whole file fails Zod validation (→ ignored) without `version: 1`.
        //
        // NOTE: this routes cline's INTERACTIVE/TUI runs through kyrisd. cline's
        // headless single-prompt path (`cline <prompt>`) does NOT apply stored
        // provider routing, so headless metering is not achievable — governance (the
        // file-hook) still fires regardless.
        if set_json_value_path(&mut config, &["version"], serde_json::json!(1)) {
            config_changed = true;
        }
        // Route the anthropic provider through kyrisd. The Anthropic AI SDK appends
        // `/messages` to baseUrl, so the kyrisd base needs the `/v1` suffix (same as
        // opencode). The gate secret + agent-id ride in custom `headers`; the agent's
        // OWN ANTHROPIC_API_KEY is deliberately NOT set — it flows from env as the
        // upstream credential kyrisd forwards and classifies.
        if set_json_string_path(
            &mut config,
            &["providers", "anthropic", "settings", "baseUrl"],
            &base_url_v1,
        ) {
            config_changed = true;
        }
        for (header, value) in [
            ("x-kyris-inbound", inbound_key),
            ("x-kyris-agent-id", agent_id),
        ] {
            if set_json_string_path(
                &mut config,
                &["providers", "anthropic", "settings", "headers", header],
                value,
            ) {
                config_changed = true;
            }
        }
        // Required entry metadata for the Zod schema (StoredProviderSettingsEntry).
        if set_json_string_path(
            &mut config,
            &["providers", "anthropic", "updatedAt"],
            "2026-01-01T00:00:00.000Z",
        ) {
            config_changed = true;
        }
        if set_json_string_path(
            &mut config,
            &["providers", "anthropic", "tokenSource"],
            "manual",
        ) {
            config_changed = true;
        }

        let mut changes = Vec::new();
        if config_changed {
            write_json_value(
                &path,
                &config,
                "cline:burn-control",
                &WellFormedJsonValidator,
            )?;
            changes.push(format!("wrote anthropic routing in {}", path.display()));
        }
        Ok(changes)
    }
    fn undo_execution_surface(&self) -> Result<(), String> {
        let hook_path = cline_hook_path()?;
        if !restore_manifest_entry_component(&hook_path, "cline:execution")? {
            super::undo::remove_file_if_exists(&hook_path)?;
        }
        Ok(())
    }
    fn undo_tool_surface(&self) -> Result<(), String> {
        super::configure::undo_json_mcp_tool_surface(self)
    }
    fn undo_burn_control_surface(&self) -> Result<(), String> {
        let path = cline_providers_path()?;
        if restore_manifest_entry_component(&path, "cline:burn-control")? {
            println!("Reverted {}", path.display());
        }
        Ok(())
    }
}
