// SPDX-FileCopyrightText: Copyright 2026 Kyris
// SPDX-License-Identifier: Apache-2.0
use std::path::PathBuf;

use crate::config_writer::{NoopValidator, WellFormedJsonValidator};
use crate::integration::{read_json_value, write_json_value};

use super::probe::{
    ProbeResult, env_file_has_var, env_loader_sourced, fingerprint, json_has_mcp_wrap, not_detected,
};
use super::registry::{
    AgentDescriptor, AllowResponse, HookProtocol, McpConfigFormat, McpConfigLocation,
    PrimaryProvider, ToolMapping, provider_env_exports, which_exists,
};

pub struct GeminiCli;

pub fn gemini_settings_path() -> Result<PathBuf, String> {
    if let Some(path) = crate::integration::find_upwards(".gemini/settings.json") {
        return Ok(path);
    }
    Ok(crate::integration::home_dir()?
        .join(".gemini")
        .join("settings.json"))
}

pub fn gemini_settings_exists() -> bool {
    gemini_settings_path().is_ok_and(|path| path.exists())
}

pub fn gemini_policies_dir() -> Result<PathBuf, String> {
    Ok(crate::integration::home_dir()?
        .join(".gemini")
        .join("policies"))
}

impl AgentDescriptor for GeminiCli {
    fn id(&self) -> &'static str {
        "gemini-cli"
    }
    fn display_name(&self) -> &'static str {
        "Gemini CLI"
    }
    fn is_installed(&self) -> bool {
        which_exists("gemini") || gemini_settings_exists()
    }
    fn probe(&self) -> ProbeResult {
        use super::profile::{AdaptedMechanism, CoverageCeiling, SurfaceState};
        let detected = gemini_settings_exists() || which_exists("gemini");
        if !detected {
            return not_detected();
        }

        let settings_path = gemini_settings_path().ok();
        let has_hook = settings_path.as_deref().is_some_and(|p| {
            crate::integration::read_json_value(p).is_ok_and(|v| {
                let serialized = serde_json::to_string(&v).unwrap_or_default();
                serialized.contains("agentpact_beforetool")
            })
        });
        let has_mcp_wrap = settings_path
            .as_deref()
            .is_some_and(|p| json_has_mcp_wrap(p, "mcpServers"));

        let has_compiled_policy = gemini_policies_dir()
            .ok()
            .map(|d| d.join("agentpact.toml"))
            .is_some_and(|p| p.exists());

        let execution = if has_hook {
            SurfaceState::adapted(AdaptedMechanism::LiveHook)
        } else if has_compiled_policy {
            SurfaceState::adapted(AdaptedMechanism::CompiledPolicy)
                .with_ceiling(CoverageCeiling::Compiled)
        } else {
            SurfaceState::none()
        };
        let tool = if has_mcp_wrap {
            SurfaceState::adapted(AdaptedMechanism::McpWrapping)
        } else {
            SurfaceState::none()
        };
        let has_env_file = env_file_has_var("gemini-cli", "GOOGLE_GEMINI_BASE_URL");
        let burn_control = if has_env_file && env_loader_sourced() {
            SurfaceState::adapted(AdaptedMechanism::EnvVarProxy)
        } else {
            SurfaceState::none()
        };

        let mut managed_files = Vec::new();
        if let Some(path) = settings_path.as_deref()
            && let Some(fp) = fingerprint(path)
        {
            managed_files.push(fp);
        }
        if let Some(fp) = gemini_policies_dir()
            .ok()
            .map(|d| d.join("agentpact.toml"))
            .and_then(|p| fingerprint(&p))
        {
            managed_files.push(fp);
        }

        ProbeResult {
            detected: true,
            execution,
            tool,
            burn_control,
            managed_files,
        }
    }
    fn kyris_content_markers(&self) -> &'static [&'static str] {
        &["agentpact_beforetool", "kyris-mcp", "Generated by Kyris"]
    }
    fn env_exports(&self, base_url: &str, inbound_key: &str) -> Vec<(String, String)> {
        let mut exports = provider_env_exports(PrimaryProvider::Google, base_url, inbound_key);
        exports.push(("GOOGLE_VERTEX_BASE_URL".to_string(), base_url.to_string()));
        exports
    }
    fn expected_surfaces(&self) -> (bool, bool, bool) {
        (true, true, true)
    }
    fn configure_execution(
        &self,
        _base_url: &str,
        _inbound_key: &str,
        _agent_specific: &std::collections::HashMap<String, String>,
    ) -> Result<Vec<String>, String> {
        let settings_path = gemini_settings_path()?;
        let script_path = settings_path
            .parent()
            .unwrap_or_else(|| std::path::Path::new("."))
            .join("hooks")
            .join("agentpact_beforetool.sh");

        let mut changes = super::configure::install_live_hook_adapter(
            "gemini-cli",
            "gemini-cli",
            "BeforeTool",
            &script_path,
            &settings_path,
            false,
        )?;

        match crate::compile_policy::compile_gemini_permissions(None) {
            Ok((rules, _)) => {
                let has_rules = rules.as_array().is_some_and(|a| !a.is_empty());
                if has_rules {
                    let toml_content = crate::compile_policy::serialize_gemini_policy_toml(&rules);
                    let policy_path = gemini_policies_dir()?.join("agentpact.toml");
                    // Compiled policy TOML is generated by kyris itself —
                    // we trust the serializer; no shape check needed beyond
                    // well-formedness, but keep it simple with NoopValidator.
                    if crate::state::write_managed_file(
                        &policy_path,
                        &toml_content,
                        "gemini-cli",
                        None,
                        &NoopValidator,
                    )? {
                        changes.push(format!("wrote {}", policy_path.display()));
                    }
                }
            }
            Err(e) => {
                changes.push(format!("warning: compiled policy skipped: {e}"));
            }
        }

        Ok(changes)
    }
    fn configure_burn_control(
        &self,
        base_url: &str,
        inbound_key: &str,
        agent_specific: &std::collections::HashMap<String, String>,
    ) -> Result<Vec<String>, String> {
        let settings_path = gemini_settings_path()?;
        let mut changes = Vec::new();

        if settings_path.exists() {
            let mut settings = read_json_value(&settings_path)?;
            let mut settings_changed =
                super::configure::apply_json_tool_filters(&mut settings, &["mcpServers"]);
            let mcp_result = super::configure::rewrite_json_mcp_servers(
                &mut settings,
                &["mcpServers"],
                base_url,
                inbound_key,
            );
            if mcp_result.changed {
                settings_changed = true;
            }
            if let Some(val) = agent_specific.get("maxSessionTurns")
                && let Ok(n) = val.parse::<u64>()
            {
                settings["maxSessionTurns"] = serde_json::json!(n);
                settings_changed = true;
            }
            if settings_changed {
                write_json_value(
                    &settings_path,
                    &settings,
                    "gemini-cli",
                    &WellFormedJsonValidator,
                )?;
                changes.push(format!("updated {}", settings_path.display()));
            }
            if !mcp_result.http_rewrites.is_empty() {
                super::configure::upsert_mcp_upstreams(&mcp_result.http_rewrites)?;
                changes.push("registered MCP upstream(s) in kyrisd.yaml".to_string());
            }
        }

        Ok(changes)
    }
    fn undo(&self) -> Result<(), String> {
        let settings_path = gemini_settings_path()?;
        if crate::state::restore_manifest_entry(&settings_path)? {
            println!("Reverted {}", settings_path.display());
        }
        let script = settings_path
            .parent()
            .unwrap_or(std::path::Path::new("."))
            .join("hooks")
            .join("agentpact_beforetool.sh");
        super::undo::remove_file_if_exists(&script)?;
        let policy = gemini_policies_dir()?.join("agentpact.toml");
        super::undo::remove_file_if_exists(&policy)?;
        Ok(())
    }
    fn undo_burn_control(&self) -> Result<(), String> {
        for path in self.burn_control_config_paths() {
            if crate::state::restore_manifest_entry(&path)? {
                println!("Reverted {}", path.display());
            }
        }
        let env_file = crate::state::env_dir()?.join("gemini-cli.sh");
        super::undo::remove_file_if_exists(&env_file)?;
        Ok(())
    }
    fn mcp_config(&self) -> Option<McpConfigLocation> {
        gemini_settings_path().ok().map(|path| McpConfigLocation {
            path,
            format: McpConfigFormat::Json {
                servers_path: vec!["mcpServers"],
            },
        })
    }
    fn burn_control_config_paths(&self) -> Vec<PathBuf> {
        gemini_settings_path().into_iter().collect()
    }
    fn hook_protocol(&self) -> Option<HookProtocol> {
        Some(HookProtocol {
            tool_name_field: "tool_name".to_string(),
            detail_fields: vec!["tool_input".to_string()],
            tool_mappings: vec![
                ToolMapping {
                    tool_name: "run_shell_command".to_string(),
                    action: "execute".to_string(),
                    detail_key: Some("command".to_string()),
                },
                ToolMapping {
                    tool_name: "read_file".to_string(),
                    action: "read".to_string(),
                    detail_key: Some("file_path".to_string()),
                },
                ToolMapping {
                    tool_name: "write_file".to_string(),
                    action: "write".to_string(),
                    detail_key: Some("file_path".to_string()),
                },
                ToolMapping {
                    tool_name: "replace".to_string(),
                    action: "write".to_string(),
                    detail_key: Some("file_path".to_string()),
                },
            ],
            default_action: "call".to_string(),
            allow_response: AllowResponse::Json {
                body: serde_json::json!({"decision": "allow"}),
            },
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn testGeminiExportsVertexBaseUrl() {
        let agent = GeminiCli;
        let exports = agent.env_exports("http://127.0.0.1:4710", "sk-test");
        let keys: Vec<&str> = exports.iter().map(|(k, _)| k.as_str()).collect();
        assert!(keys.contains(&"GOOGLE_GEMINI_BASE_URL"));
        assert!(keys.contains(&"GOOGLE_VERTEX_BASE_URL"));
        assert!(keys.contains(&"GEMINI_API_KEY_AUTH_MECHANISM"));
    }
}
