// SPDX-FileCopyrightText: Copyright 2026 Kyris
// SPDX-License-Identifier: Apache-2.0
//! Per-agent hook-bridge templates — the adapter scripts the generic engine
//! installs (`install_file` op) to speak each agent's hook API. These are the
//! one genuinely agent-specific *asset* in the data-driven model (the *fact*
//! that an agent runs a `command|cjs_file|js_plugin|nested_config` hook is
//! declared in the agent's document; the script that satisfies that contract is
//! kyris's adapter, resolved here by name).
//!
//! Templates carry `__SPAWN_TIMEOUT_MS__` (and similar) substitution markers the
//! engine fills from the agent's declared hook runtime.

/// Resolve a bridge template by the name used in a document's
/// `install_file.template`. Returns `None` for an unknown name (the engine then
/// fails the configure op loudly rather than installing nothing).
#[must_use]
pub fn bridge_template(name: &str) -> Option<&'static str> {
    match name {
        "cline_pretooluse" => Some(CLINE_PRETOOLUSE),
        _ => None,
    }
}

/// The cline file-hook bridge. cline delivers a different hook shape than the
/// native-hook agents (JSON tool context in, a JSON `{cancel}` control out), so
/// this reshapes cline's payload into the kyris payload, asks the shared decision
/// engine (`kyris hook check --agent cline` → agentpactd), and blocks the tool by
/// emitting `{cancel:true}` on deny. `__SPAWN_TIMEOUT_MS__` is substituted from
/// the declared hook runtime (cline SIGKILLs the hook at 120s and proceeds
/// fail-open, so the bridge must resolve strictly inside that window).
const CLINE_PRETOOLUSE: &str = r#"// SPDX-FileCopyrightText: Copyright 2026 Kyris
// SPDX-License-Identifier: Apache-2.0
// Generated by Kyris — AgentPact live governance for cline (file-hook bridge).
// cline runs this on every tool call (PreToolUse -> tool_call), blocking. It
// reshapes cline's payload into the kyris hook payload, asks the shared decision
// engine (kyris hook check -> agentpactd), and blocks the tool by emitting a
// {cancel:true} control object when governance denies.
const { spawnSync } = require("node:child_process")
const { existsSync } = require("node:fs")
const { homedir } = require("node:os")

// Prefer the managed copy, then well-known install paths, then PATH — mirrors the
// shell adapter's resolution (a real binary at a known path over whatever PATH is).
function kyrisBin() {
  for (const c of [
    homedir() + "/.kyris/bin/kyris",
    homedir() + "/.local/bin/kyris",
    "/opt/homebrew/bin/kyris",
    "/usr/local/bin/kyris",
  ]) {
    if (existsSync(c)) return c
  }
  return "kyris"
}

// cline runtime tool name -> the detail kyris governs (command for execute,
// path for write, patch text for apply_patch). cline accepts MANY run_commands
// shapes (schemas.ts RunCommands/StructuredCommands unions): commands as a
// string[] or string, command/cmd singletons, a bare string or string[], and
// structured {command,args} entries (Windows). Normalize all of them to one
// compound line so agentpactd splits it into per-segment decisions; an
// unrecognized shape yields "" (empty detail → governed as an empty execute,
// never silently skipped).
function oneCommand(c) {
  if (typeof c === "string") return c
  if (c && typeof c === "object" && typeof c.command === "string") {
    return Array.isArray(c.args) && c.args.length ? c.command + " " + c.args.join(" ") : c.command
  }
  return ""
}
function detailFor(name, input) {
  // apply_patch: bare patch string or {input: patchString}.
  if (name === "apply_patch") {
    if (typeof input === "string") return input
    return input && typeof input.input === "string" ? input.input : ""
  }
  if (name === "run_commands") {
    if (typeof input === "string") return input
    if (Array.isArray(input)) return input.map(oneCommand).filter(Boolean).join(" && ")
    const i = input || {}
    const list = i.commands ?? i.command ?? i.cmd
    if (Array.isArray(list)) return list.map(oneCommand).filter(Boolean).join(" && ")
    return oneCommand(list)
  }
  const i = input || {}
  if (name === "editor") return typeof i.path === "string" ? i.path : ""
  return ""
}

let raw = ""
process.stdin.on("data", (d) => { raw += d })
process.stdin.on("end", () => {
  let p = {}
  try { p = JSON.parse(raw) } catch { p = {} }
  const tc = p.tool_call || {}
  // cwd is the permitted-domain anchor agentpactd resolves policy from; cline has
  // no top-level cwd, so use the first workspace root.
  const cwd = (Array.isArray(p.workspaceRoots) && p.workspaceRoots[0]) ||
    (p.workspaceInfo && p.workspaceInfo.rootPath) || process.cwd()
  const payload = JSON.stringify({
    tool_name: tc.name,
    tool_input: { detail: detailFor(tc.name, tc.input) },
    cwd,
  })
  const res = spawnSync(kyrisBin(), ["hook", "check", "--agent", "cline"], {
    input: payload,
    cwd,
    encoding: "utf8",
    timeout: __SPAWN_TIMEOUT_MS__,
    env: { ...process.env, KYRIS_GOVERNED_SUBPROCESS: "cline" },
  })
  // A hung engine fails CLOSED: cline kills this hook shortly after and then
  // RUNS the command (fail-open, 120s), so an unresolved check must become a
  // deny while we can still deliver one. Only a missing/unrunnable binary fails
  // open ("kyris not installed -> ungoverned", matching the shell adapter).
  if (res.error && res.error.code === "ETIMEDOUT") {
    process.stdout.write(JSON.stringify({ cancel: true, errorMessage: "kyris governance check timed out before a decision" }))
    return
  }
  if (res.error) { process.stdout.write("{}"); return }
  // exit 0 = allow; nonzero (2 = deny). cline reads the JSON control object
  // from stdout (not the exit code). `{cancel:true}` STOPS the agent run
  // (cline maps it to ControlledStopError — it does not gracefully skip just
  // this tool, and it drops `errorMessage`, so the model is not told why).
  // Heavier than a per-tool deny, but safe: nothing ungoverned runs. The
  // errorMessage is kept anyway for the cline-side log / future versions.
  if (res.status !== 0) {
    const reason = (res.stderr || res.stdout || "").trim().replace(/^\[agentpact\]\s*/, "")
    process.stdout.write(JSON.stringify({ cancel: true, errorMessage: reason || "blocked by kyris governance" }))
  } else {
    process.stdout.write("{}")
  }
})
"#;
