// SPDX-FileCopyrightText: Copyright 2026 Kyris
// SPDX-License-Identifier: Apache-2.0
//! Self-contained HTML scan report with inline SVG severity donut chart.
//! No external assets — the output file opens in any browser with no network.

use std::fmt::Write as _;

use crate::scan::scanner::{Finding, FindingCategory, RiskLevel, Severity, risk_level};

const CRITICAL_COLOR: &str = "#dc2626";
const HIGH_COLOR: &str = "#ea580c";
const MEDIUM_COLOR: &str = "#d97706";
const LOW_COLOR: &str = "#2563eb";
const INFO_COLOR: &str = "#6b7280";

/// Builds the complete self-contained HTML string. Exposed so `mod.rs` can
/// write it directly to a file when `--output PATH` is provided.
pub fn build_html(findings: &[Finding]) -> String {
    let timestamp = now_utc();
    let total = findings.len();
    let score: u32 = findings.iter().map(|f| f.severity as u32).sum();
    let level = risk_level(score);
    let (level_color, level_label) = level_appearance(level);
    let plural = if total == 1 { "" } else { "s" };

    let chart = donut_svg(findings);
    let legend = legend_html(findings);
    let findings_body = findings_html(findings);
    let css = css();

    let clean_banner = if total == 0 {
        r#"<div class="clean">&#10003; No findings detected &mdash; environment looks good.</div>"#
    } else {
        ""
    };

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Kyris Security Scan Report</title>
<style>{css}</style>
</head>
<body>
<header>
<div class="inner">
<div class="logo">Kyris</div>
<h1>Security Scan Report</h1>
<p class="ts">Generated {timestamp}</p>
</div>
</header>
<main class="inner">
<section class="summary">
<div class="risk-card" style="border-top:4px solid {level_color}">
<div class="big-score" style="color:{level_color}">{score}</div>
<div class="level-lbl" style="color:{level_color}">{level_label}</div>
<div class="sub">risk score</div>
<hr>
<div class="count">{total} finding{plural}</div>
</div>
<div class="chart-card">
{chart}
{legend}
</div>
</section>
{clean_banner}
{findings_body}
<section class="cta">
<h2>Govern your AI agents at scale</h2>
<p>Kyris App adds policy sync, spend enforcement, team visibility, and approval workflows &mdash; built on the same open-source governance engine.</p>
<a href="https://kyris.app" class="cta-btn">Try Kyris App &#x2192;</a>
</section>
</main>
<footer>Generated by <a href="https://kyris.app">Kyris</a> &middot; Open-source AI governance</footer>
</body>
</html>"#
    )
}

// ---------------------------------------------------------------------------
// SVG donut chart
//
// Note: SVG attributes like stroke="#e2e8f0" contain the sequence `"#` which
// would prematurely terminate r#"..."# raw strings. Use r##"..."## for any
// format! string that embeds literal hex colours as attribute values.
// ---------------------------------------------------------------------------

fn donut_svg(findings: &[Finding]) -> String {
    let cx = 90.0f64;
    let cy = 90.0f64;
    let r = 62.0f64;
    let sw = 26.0f64;
    let circ = 2.0 * std::f64::consts::PI * r; // ≈ 389.56

    if findings.is_empty() {
        // r## avoids the "# termination problem with fill="#166534" etc.
        return format!(
            r##"<svg viewBox="0 0 180 180" width="150" height="150" xmlns="http://www.w3.org/2000/svg"><circle cx="{cx}" cy="{cy}" r="{r}" fill="none" stroke="#dcfce7" stroke-width="{sw}"/><text x="{cx}" y="{cy}" text-anchor="middle" dominant-baseline="central" font-size="13" fill="#166534" font-weight="600">Clean</text></svg>"##
        );
    }

    let total = findings.len();

    // Open tag — no hex colours, r# is fine.
    let mut svg = String::from(
        r#"<svg viewBox="0 0 180 180" width="150" height="150" xmlns="http://www.w3.org/2000/svg">"#,
    );

    // Background track — r## because stroke="#e2e8f0" contains "# .
    let _ = write!(
        svg,
        r##"<circle cx="{cx}" cy="{cy}" r="{r}" fill="none" stroke="#e2e8f0" stroke-width="{sw}"/>"##
    );

    // Coloured segments. `color` is a variable so the template itself has no
    // literal "# — escaped-quote style keeps things simple.
    let segments = [
        (count_sev(findings, Severity::Critical), CRITICAL_COLOR),
        (count_sev(findings, Severity::High), HIGH_COLOR),
        (count_sev(findings, Severity::Medium), MEDIUM_COLOR),
        (count_sev(findings, Severity::Low), LOW_COLOR),
        (count_sev(findings, Severity::Info), INFO_COLOR),
    ];

    // stroke-dashoffset = circ − cumulative_start positions each segment
    // exactly after the previous one. rotate(-90) moves origin to 12 o'clock.
    let mut cumulative = 0.0f64;
    for (count, color) in &segments {
        if *count == 0 {
            continue;
        }
        // Severity slice counts and total are small (always under a million);
        // casting to f64 here loses no precision in any practical scan run.
        #[allow(clippy::cast_precision_loss)]
        let frac = *count as f64 / total as f64;
        let dash = frac * circ;
        let gap = circ - dash;
        let offset = circ - cumulative;
        let _ = write!(
            svg,
            "<circle cx=\"{cx}\" cy=\"{cy}\" r=\"{r}\" fill=\"none\" \
             stroke=\"{color}\" stroke-width=\"{sw}\" \
             stroke-dasharray=\"{dash:.2} {gap:.2}\" \
             stroke-dashoffset=\"{offset:.2}\" \
             transform=\"rotate(-90 {cx} {cy})\"/>"
        );
        cumulative += dash;
    }

    // Centre labels — r## because fill="#1e293b" and fill="#64748b" contain "#.
    let y1 = cy - 8.0;
    let y2 = cy + 12.0;
    let _ = write!(
        svg,
        r##"<text x="{cx}" y="{y1}" text-anchor="middle" dominant-baseline="central" font-size="22" fill="#1e293b" font-weight="700">{total}</text><text x="{cx}" y="{y2}" text-anchor="middle" font-size="9" fill="#64748b">findings</text></svg>"##
    );

    svg
}

// ---------------------------------------------------------------------------
// Severity legend
// ---------------------------------------------------------------------------

fn legend_html(findings: &[Finding]) -> String {
    let rows = [
        (
            "Critical",
            CRITICAL_COLOR,
            count_sev(findings, Severity::Critical),
        ),
        ("High", HIGH_COLOR, count_sev(findings, Severity::High)),
        (
            "Medium",
            MEDIUM_COLOR,
            count_sev(findings, Severity::Medium),
        ),
        ("Low", LOW_COLOR, count_sev(findings, Severity::Low)),
        ("Info", INFO_COLOR, count_sev(findings, Severity::Info)),
    ];
    let mut html = String::from(r#"<div class="legend">"#);
    for (label, color, count) in &rows {
        if *count == 0 {
            continue;
        }
        let _ = write!(
            html,
            r#"<div class="legend-row"><span class="dot" style="background:{color}"></span><span class="lbl">{label}</span><span class="cnt">{count}</span></div>"#
        );
    }
    html.push_str("</div>");
    html
}

// ---------------------------------------------------------------------------
// Findings grouped by category
// ---------------------------------------------------------------------------

fn findings_html(findings: &[Finding]) -> String {
    if findings.is_empty() {
        return String::new();
    }
    let categories = [
        (FindingCategory::ApiKey, "API Keys"),
        (FindingCategory::UngoverndAgent, "Ungoverned Agents"),
        (
            FindingCategory::DegradedAgent,
            "Degraded Agent Integrations",
        ),
        (FindingCategory::VendorNativeAgent, "Vendor-Governed Agents"),
        (FindingCategory::UngoverndMcp, "Ungoverned MCP Servers"),
        (FindingCategory::LlmTraffic, "LLM Traffic"),
    ];
    let mut html = String::new();
    for (cat, label) in &categories {
        let group: Vec<&Finding> = findings.iter().filter(|f| f.category == *cat).collect();
        if group.is_empty() {
            continue;
        }
        let n = group.len();
        let plural = if n == 1 { "" } else { "s" };
        let _ = write!(
            html,
            r#"<div class="cat"><div class="cat-hdr"><span>{label}</span><span>{n} finding{plural}</span></div>"#
        );
        for f in &group {
            html.push_str(&finding_html(f));
        }
        html.push_str("</div>");
    }
    html
}

fn finding_html(f: &Finding) -> String {
    let (sev_color, sev_label) = sev_appearance(f.severity);
    let loc = match f.location.line {
        Some(l) => format!("{}:{l}", he(&f.location.path)),
        None => he(&f.location.path),
    };
    let evidence_row = match &f.evidence {
        Some(ev) => format!(
            r#"<div class="meta-row"><span class="meta-lbl">Evidence</span><code class="ev">{}</code></div>"#,
            he(ev)
        ),
        None => String::new(),
    };
    format!(
        r#"<div class="finding"><div class="f-hdr"><span class="badge" style="background:{sev_color}">{sev_label}</span><span class="f-title">{}</span></div><div class="f-desc">{}</div><div class="f-meta"><div class="meta-row"><span class="meta-lbl">Location</span><code class="loc">{loc}</code></div>{evidence_row}<div class="meta-row"><span class="meta-lbl">Fix</span><span class="fix">{}</span></div></div></div>"#,
        he(&f.title),
        he(&f.description),
        he(&f.remediation),
    )
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn count_sev(findings: &[Finding], s: Severity) -> usize {
    findings.iter().filter(|f| f.severity == s).count()
}

fn sev_appearance(s: Severity) -> (&'static str, &'static str) {
    match s {
        Severity::Critical => (CRITICAL_COLOR, "CRITICAL"),
        Severity::High => (HIGH_COLOR, "HIGH"),
        Severity::Medium => (MEDIUM_COLOR, "MEDIUM"),
        Severity::Low => (LOW_COLOR, "LOW"),
        Severity::Info => (INFO_COLOR, "INFO"),
    }
}

fn level_appearance(l: RiskLevel) -> (&'static str, &'static str) {
    match l {
        RiskLevel::Critical => (CRITICAL_COLOR, "CRITICAL"),
        RiskLevel::High => (HIGH_COLOR, "HIGH"),
        RiskLevel::Medium => (MEDIUM_COLOR, "MEDIUM"),
        RiskLevel::Low => ("#16a34a", "LOW"),
    }
}

/// HTML-escapes the five special characters. No external crate needed.
fn he(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            c => out.push(c),
        }
    }
    out
}

fn now_utc() -> String {
    chrono::Utc::now().format("%Y-%m-%d %H:%M UTC").to_string()
}

// ---------------------------------------------------------------------------
// Inline CSS — self-contained, no external deps.
// Hex colours here are safe because they appear after ":" not after """,
// so the r#"..."# raw string is not terminated early.
// ---------------------------------------------------------------------------

fn css() -> &'static str {
    r"*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f8fafc;color:#1e293b;line-height:1.6;font-size:15px}
a{color:#2563eb}
.inner{max-width:920px;margin:0 auto;padding:0 1.25rem}
header{background:#0f172a;color:#f1f5f9;padding:1.5rem 0}
header .inner{display:flex;flex-direction:column;gap:.15rem}
.logo{font-size:.85rem;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:.08em}
h1{font-size:1.6rem;font-weight:700}
.ts{color:#64748b;font-size:.8rem}
main.inner{padding-top:2rem;padding-bottom:3rem}
.summary{display:flex;gap:1.5rem;align-items:stretch;margin-bottom:2rem;flex-wrap:wrap}
.risk-card{background:#fff;border-radius:10px;padding:1.5rem;box-shadow:0 1px 4px rgba(0,0,0,.08);min-width:155px;text-align:center;flex-shrink:0}
.big-score{font-size:3rem;font-weight:800;line-height:1}
.level-lbl{font-size:.78rem;font-weight:700;letter-spacing:.08em;margin-top:.2rem}
.sub{font-size:.72rem;color:#94a3b8;margin-bottom:.75rem}
hr{border:none;border-top:1px solid #e2e8f0;margin:.75rem 0}
.count{font-size:.9rem;color:#475569}
.chart-card{background:#fff;border-radius:10px;padding:1.25rem 1.5rem;box-shadow:0 1px 4px rgba(0,0,0,.08);display:flex;align-items:center;gap:1.5rem;flex:1;min-width:260px}
.legend{flex:1}
.legend-row{display:flex;align-items:center;gap:.5rem;margin-bottom:.4rem;font-size:.85rem}
.dot{width:11px;height:11px;border-radius:50%;flex-shrink:0}
.lbl{color:#334155;flex:1}
.cnt{font-weight:700;color:#1e293b}
.clean{background:#dcfce7;color:#166534;border:1px solid #bbf7d0;border-radius:8px;padding:.9rem 1.25rem;text-align:center;font-weight:500;margin-bottom:2rem}
.cat{background:#fff;border-radius:10px;box-shadow:0 1px 4px rgba(0,0,0,.08);margin-bottom:1.5rem;overflow:hidden}
.cat-hdr{padding:.65rem 1.25rem;background:#f8fafc;border-bottom:1px solid #e2e8f0;font-weight:600;font-size:.85rem;color:#475569;display:flex;justify-content:space-between}
.finding{padding:1rem 1.25rem;border-bottom:1px solid #f1f5f9}
.finding:last-child{border-bottom:none}
.f-hdr{display:flex;align-items:baseline;gap:.6rem;margin-bottom:.3rem}
.badge{font-size:.68rem;font-weight:700;letter-spacing:.06em;padding:.12rem .38rem;border-radius:3px;color:#fff;white-space:nowrap}
.f-title{font-weight:600;font-size:.92rem;color:#1e293b}
.f-desc{color:#475569;font-size:.85rem;margin-bottom:.5rem}
.f-meta{font-size:.8rem;display:flex;flex-direction:column;gap:.25rem}
.meta-row{display:flex;align-items:baseline;gap:.4rem;flex-wrap:wrap}
.meta-lbl{color:#94a3b8;font-weight:600;white-space:nowrap;min-width:60px}
.loc,.ev{font-family:'SF Mono',Menlo,Monaco,Consolas,monospace;font-size:.78rem;color:#475569;background:#f1f5f9;padding:.1rem .35rem;border-radius:3px;overflow-wrap:anywhere}
.fix{color:#15803d}
.cta{background:#0f172a;color:#f1f5f9;border-radius:12px;padding:2rem;text-align:center;margin:2.5rem 0 1rem}
.cta h2{font-size:1.35rem;margin-bottom:.5rem}
.cta p{color:#94a3b8;font-size:.9rem;margin-bottom:1.25rem}
.cta-btn{display:inline-block;background:#2563eb;color:#fff;padding:.65rem 1.75rem;border-radius:6px;text-decoration:none;font-weight:600;font-size:.9rem}
footer{text-align:center;color:#94a3b8;font-size:.78rem;padding:1rem 0 2rem}
footer a{color:#64748b;text-decoration:none}
@media(max-width:580px){.summary{flex-direction:column}.chart-card{flex-direction:column;align-items:flex-start}}"
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scan::scanner::{FindingCategory, FindingLocation};

    fn make_finding(severity: Severity, category: FindingCategory) -> Finding {
        Finding {
            category,
            severity,
            title: "Test <finding> & check".to_string(),
            description: "A \"description\" with 'quotes'.".to_string(),
            location: FindingLocation {
                path: "/path/to/file.rs".to_string(),
                line: Some(42),
            },
            evidence: Some("sk-ant-abc123...".to_string()),
            remediation: "Fix it now.".to_string(),
        }
    }

    #[test]
    fn testBuildHtmlIsValidHtml() {
        let html = build_html(&[]);
        assert!(html.starts_with("<!DOCTYPE html>"));
        assert!(html.contains("<html"));
        assert!(html.contains("</html>"));
        assert!(html.contains("</head>"));
        assert!(html.contains("</body>"));
    }

    #[test]
    fn testBuildHtmlContainsTitleAndTimestamp() {
        let html = build_html(&[]);
        assert!(html.contains("Kyris Security Scan Report"));
        assert!(html.contains("UTC")); // timestamp always ends in UTC
    }

    #[test]
    fn testBuildHtmlContainsCta() {
        let html = build_html(&[]);
        assert!(html.contains("kyris.app"));
        assert!(html.contains("Kyris App"));
    }

    #[test]
    fn testBuildHtmlNoFindingsShowsCleanBanner() {
        let html = build_html(&[]);
        assert!(html.contains("No findings detected"));
        // No category section divs (the CSS class exists but no div should use it).
        assert!(!html.contains(r#"class="cat-hdr""#));
    }

    #[test]
    fn testBuildHtmlNoFindingsChartIsGreenClean() {
        let html = build_html(&[]);
        assert!(html.contains("Clean")); // empty-state donut label
        assert!(html.contains("#dcfce7")); // green track colour
    }

    #[test]
    fn testBuildHtmlWithFindingsShowsFindings() {
        let findings = vec![
            make_finding(Severity::Critical, FindingCategory::ApiKey),
            make_finding(Severity::High, FindingCategory::LlmTraffic),
        ];
        let html = build_html(&findings);
        assert!(!html.contains("No findings detected"));
        assert!(html.contains("CRITICAL"));
        assert!(html.contains("HIGH"));
        assert!(html.contains("API Keys"));
        assert!(html.contains("LLM Traffic"));
    }

    #[test]
    fn testBuildHtmlEscapesSpecialChars() {
        let html = build_html(&[make_finding(Severity::Info, FindingCategory::ApiKey)]);
        assert!(html.contains("Test &lt;finding&gt; &amp; check"));
        assert!(html.contains("&quot;description&quot;"));
        assert!(html.contains("it&#39;s") || html.contains("&#39;")); // single quote escaped
    }

    #[test]
    fn testBuildHtmlShowsLineNumber() {
        let html = build_html(&[make_finding(Severity::High, FindingCategory::ApiKey)]);
        assert!(html.contains("file.rs:42"));
    }

    #[test]
    fn testBuildHtmlScoreAndLevel() {
        let findings = vec![make_finding(Severity::Critical, FindingCategory::ApiKey)];
        let html = build_html(&findings);
        assert!(html.contains(">10<")); // risk score
        assert!(html.contains("CRITICAL"));
    }

    #[test]
    fn testBuildHtmlFindingCountPlural() {
        let html = build_html(&[
            make_finding(Severity::High, FindingCategory::ApiKey),
            make_finding(Severity::High, FindingCategory::ApiKey),
        ]);
        assert!(html.contains("2 findings"));
    }

    #[test]
    fn testBuildHtmlFindingCountSingular() {
        let html = build_html(&[make_finding(Severity::High, FindingCategory::ApiKey)]);
        // "1 finding" must appear (without trailing 's') somewhere in the html
        assert!(html.contains("1 finding"));
    }

    #[test]
    fn testBuildHtmlIsSelfContained() {
        let html = build_html(&[make_finding(Severity::High, FindingCategory::ApiKey)]);
        assert!(!html.contains("<link")); // no external stylesheet
        assert!(!html.contains("<script")); // no script tags
        assert!(!html.contains("src=")); // no external src references
    }

    #[test]
    fn testBuildHtmlOnlyExternalHrefIsKyrisApp() {
        let html = build_html(&[make_finding(Severity::High, FindingCategory::ApiKey)]);
        // The only http/https href must be kyris.app.
        for href in html.split("href=\"") {
            let url = href.split('"').next().unwrap_or("");
            if url.starts_with("http") {
                assert!(
                    url.starts_with("https://kyris.app"),
                    "unexpected external href: {url}"
                );
            }
        }
    }

    #[test]
    fn testBuildHtmlGroupsByCategory() {
        let findings = vec![
            make_finding(Severity::Critical, FindingCategory::ApiKey),
            make_finding(Severity::High, FindingCategory::UngoverndAgent),
        ];
        let html = build_html(&findings);
        assert!(html.contains("API Keys"));
        assert!(html.contains("Ungoverned Agents"));
    }

    #[test]
    fn testBuildHtmlOmitsEmptyCategories() {
        let findings = vec![make_finding(Severity::Critical, FindingCategory::ApiKey)];
        let html = build_html(&findings);
        assert!(!html.contains("Ungoverned Agents"));
        assert!(!html.contains("LLM Traffic"));
    }

    #[test]
    fn testDonutSvgEmpty() {
        let svg = donut_svg(&[]);
        assert!(svg.contains("<svg"));
        assert!(svg.contains("Clean"));
        assert!(svg.contains("#dcfce7"));
    }

    #[test]
    fn testDonutSvgWithFindings() {
        let findings = vec![
            make_finding(Severity::Critical, FindingCategory::ApiKey),
            make_finding(Severity::High, FindingCategory::ApiKey),
        ];
        let svg = donut_svg(&findings);
        assert!(svg.contains(CRITICAL_COLOR));
        assert!(svg.contains(HIGH_COLOR));
        assert!(svg.contains(">2<") || svg.contains(">2\n") || svg.contains("2</text>"));
    }

    #[test]
    fn testDonutSvgSegmentCount() {
        // Only non-zero severities should produce a segment circle.
        let findings = vec![make_finding(Severity::Critical, FindingCategory::ApiKey)];
        let svg = donut_svg(&findings);
        // One background track + one red segment = exactly 2 <circle> elements.
        assert_eq!(svg.matches("<circle").count(), 2);
    }

    #[test]
    fn testLegendHidesZeroSeverities() {
        let findings = vec![make_finding(Severity::Critical, FindingCategory::ApiKey)];
        let html = legend_html(&findings);
        assert!(html.contains("Critical"));
        assert!(!html.contains("High")); // zero — must not appear
        assert!(!html.contains("Info"));
    }

    #[test]
    fn testHtmlEscapeAllSpecialChars() {
        assert_eq!(he("a&b"), "a&amp;b");
        assert_eq!(he("<tag>"), "&lt;tag&gt;");
        assert_eq!(he("\"hi\""), "&quot;hi&quot;");
        assert_eq!(he("it's"), "it&#39;s");
        assert_eq!(he("plain"), "plain");
    }

    #[test]
    fn testEvidenceRowPresentWhenProvided() {
        let html = build_html(&[make_finding(Severity::High, FindingCategory::ApiKey)]);
        assert!(html.contains("class=\"ev\""));
        assert!(html.contains("sk-ant-abc123"));
    }

    #[test]
    fn testNoEvidenceRowWhenAbsent() {
        let mut f = make_finding(Severity::High, FindingCategory::ApiKey);
        f.evidence = None;
        let html = build_html(&[f]);
        assert!(!html.contains("class=\"ev\""));
    }
}
